name: Deploy Lycosidae Main

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug Secrets
      run: |
        echo "🔍 Verificando secrets..."
        echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
        echo "VPS_USERNAME: ${{ secrets.VPS_USERNAME }}"
        echo "VPS_PASSWORD definido: ${{ secrets.VPS_PASSWORD != '' }}"
        
        if [ -z "${{ secrets.VPS_HOST }}" ]; then
          echo "❌ ERRO: VPS_HOST não está definido!"
          exit 1
        fi
        
        if [ -z "${{ secrets.VPS_USERNAME }}" ]; then
          echo "❌ ERRO: VPS_USERNAME não está definido!"
          exit 1
        fi
        
        if [ -z "${{ secrets.VPS_PASSWORD }}" ]; then
          echo "❌ ERRO: VPS_PASSWORD não está definido!"
          exit 1
        fi
        
        echo "✅ Todas as secrets estão definidas!"
    
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          echo "✅ Conexão SSH funcionou!"
          echo "Usuário: $(whoami)"
          echo "Hostname: $(hostname)"
          echo "Data: $(date)"
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          set -e
          echo "🚀 Iniciando deploy do Lycosidae (Repositório Principal)..."
          
          # Ir para o diretório do projeto
          cd /root/Lycosidae-Project/Lycosidae
          
          # Atualizar repositório principal
          echo "🔄 Atualizando repositório principal..."
          git pull origin main
          
          # Executar script de deploy
          echo "🔧 Executando script de deploy..."
          chmod +x deploy.sh
          ./deploy.sh
          
          echo "✅ Deploy do Lycosidae (Repositório Principal) concluído com sucesso!"