name: Deploy Lycosidae

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
      interpreter: ${{ steps.changes.outputs.interpreter }}
      orchester: ${{ steps.changes.outputs.orchester }}
      compose: ${{ steps.changes.outputs.compose }}
      any-changes: ${{ steps.changes.outputs.any-changes }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          frontend:
            - 'src/Frontend-Lycosidae/**'
          backend:
            - 'src/Backend-Lycosidae/**'
          interpreter:
            - 'src/Interpreter-Lycosidae/**'
          orchester:
            - 'src/Orchester-Lycosidae/**'
          compose:
            - 'src/compose.yaml'
            - 'src/.env*'
          any-changes:
            - 'src/**'

  deploy:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.any-changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -e
          echo "🚀 Iniciando deploy do Lycosidae..."
          
          # Ir para o diretório do projeto
          cd /root/Lycosidae-Project/Lycosidae
          
          # Atualizar repositório principal
          echo "🔄 Atualizando repositório principal..."
          git pull origin main
          
          # Executar script de deploy
          echo "🔧 Executando script de deploy..."
          chmod +x deploy.sh
          ./deploy.sh
          
          echo "✅ Deploy concluído com sucesso!"