name: Deploy Lycosidae Main

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -e
          echo "🚀 Iniciando deploy do Lycosidae (Repositório Principal)..."
          
          # Ir para o diretório do projeto
          cd /root/Lycosidae-Project/Lycosidae
          
          # Atualizar repositório principal
          echo "🔄 Atualizando repositório principal..."
          git pull origin main
          
          # Executar script de deploy
          echo "🔧 Executando script de deploy..."
          chmod +x deploy.sh
          ./deploy.sh
          
          echo "✅ Deploy do Lycosidae (Repositório Principal) concluído com sucesso!"
